baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'K dev blog'
theme = 'ananke'

[params]
author = "K"

[params.shareButtons]
networks = [ "facebook", "twitter", "email", "reddit" ]
size = "small"
icon = "solid"
buttonMargin = "0.2em"